---
name: Run Test coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rust-clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: ⚡ Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
            target
          key: debug-${{ runner.os }}-stable
          restore-keys: |
            debug-${{ runner.os }}-
      - name: Install rust
        run: |
          rustup install stable
          rustup default stable
          rustup show
      - name: Install required cargo packages for reporting format
        run: cargo install cargo-tarpaulin
      - name: Run Tarpaulin (Test coverage)
        run: |
          cargo tarpaulin --all-features --coveralls ${{ secrets.COVERALLS_KEY }}
