---
name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Bump patch/minor/major
        default: "patch"
        type: "string"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_PUBLISH_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
          rustup show
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install required cargo packages for creating release
        run: |
          cargo install cargo-smart-release
      - name: Run cargo release process
        run: |
          cargo smart-release --update-crates-index --bump ${{ github.event.inputs.version }}
