---
name: Run Test and report Test coverage

on:
  push:
    branches:
      - main
    files:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/codequality.yaml'

  pull_request:
    branches:
      - main
    files:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/codequality.yaml'

jobs:
  tarpaulin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
          rustup show
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install required cargo packages for reporting format
        run: cargo install cargo-tarpaulin
      - name: Run Tarpaulin (Test coverage)
        run: |
          cargo tarpaulin --all-features --coveralls ${{ secrets.COVERALLS_KEY }}
